using System.Diagnostics;
using Google.Protobuf;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using SimpleNetEngine.Infrastructure.Telemetry;
using SimpleNetEngine.Node.Core;
using SimpleNetEngine.Node.Network;
using SimpleNetEngine.Protocol.Packets;
using SimpleNetEngine.ProtoGenerator;

namespace SimpleNetEngine.Game.Core;

/// <summary>
/// GameServer의 Node 간 RPC 패킷 처리기.
/// INodeDispatcher를 사용하여 [NodeController] + [NodePacketHandler] 기반 핸들러로 라우팅합니다.
/// Sequential 모드로 동작하여 모든 패킷을 단일 스레드에서 순차 처리합니다.
///
/// 역할:
/// - NodePacket 수신 → INodeDispatcher 호출
///
/// 노드 참여/이탈 관리는 NodeManager가 이미 담당하므로
/// OnJoinNode / OnLeaveNode 오버라이드는 하지 않습니다.
/// </summary>
public class GameNodeEventHandler : SequentialNodeEventHandler
{
    private readonly INodeResponser _responser;
    private readonly IServiceScopeFactory _scopeFactory;
    private readonly INodeDispatcher _dispatcher;

    public GameNodeEventHandler(
        ILogger<GameNodeEventHandler> logger,
        INodeDispatcher dispatcher,
        INodeResponser responser,
        IServiceScopeFactory scopeFactory)
        : base(logger)
    {
        _dispatcher = dispatcher;
        _responser = responser;
        _scopeFactory = scopeFactory;
    }

    /// <summary>
    /// NodePacket을 INodeDispatcher로 직접 라우팅
    /// QueuedResponseWriter에 의해 단일 스레드에서 순차적으로 호출됩니다.
    /// </summary>
    protected override async Task ProcessPacketInternalAsync(NodePacket packet)
    {
        IMessage? response = null;
        using (packet)
        {
            try
            {
                // Distributed Tracing: Server span (샘플링 기반)
                var msgName = AutoGeneratedParsers.GetNameById(packet.Header.MsgId);
                using var activity = TelemetryHelper.Source.HasListeners()
                    ? TelemetryHelper.ExtractAndStartActivity(in packet.Header, $"Node.RPC {msgName}", ActivityKind.Server)
                    : null;
                if (activity != null)
                {
                    activity.SetTag("rpc.system", "netmq");
                    activity.SetTag("rpc.method", msgName);
                    activity.SetTag("net.peer.id", packet.Header.Source);
                }

                await using var scope = _scopeFactory.CreateAsyncScope();
                response = await _dispatcher.DispatchAsync(scope.ServiceProvider, packet);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Error processing node packet in GameNodeEventHandler");
            }

            if (response != null)
                _responser.Response(packet.Header, response);
        }
    }
}
