using System.Diagnostics;
using Google.Protobuf;
using Microsoft.Extensions.Options;
using SimpleNetEngine.Infrastructure.Telemetry;
using SimpleNetEngine.Protocol.Packets;
using SimpleNetEngine.Node.Config;
using SimpleNetEngine.Node.Core;
using SimpleNetEngine.Node.Utils;
using SimpleNetEngine.ProtoGenerator;

namespace SimpleNetEngine.Node.Network;

public class NodeSender(
    IOptions<NodeConfig> nodeConfig,
    INodeManager nodeManager,
    RequestCache<NodePacket> requestCache,
    NodeCommunicator nodeCommunicator)
    : INodeSender
{
    private NodeConfig NodeConfig { get; } = nodeConfig.Value;

    public Task<TResponse> RequestApiAsync<TRequest, TResponse>(long actorId, string apiName,
        TRequest request)
        where TRequest : IMessage<TRequest>, new()
        where TResponse : IMessage<TResponse>, new()
    {
        var targetNode = nodeManager.RoundRobinByApiName(apiName);
        if (targetNode is null || targetNode.IsClose)
            throw new InvalidOperationException($"Failed to find target node apiName:{apiName}");

        return RequestInternalAsync<TRequest, TResponse>(actorId, targetNode, request);
    }

    public Task<TResponse> RequestApiAsync<TRequest, TResponse>(string apiName, TRequest request) 
        where TRequest : IMessage<TRequest>, new() 
        where TResponse : IMessage<TResponse>, new()
    {
        return RequestApiAsync<TRequest, TResponse>(0, apiName, request);
    }

    public Task<TResponse> RequestAsync<TRequest, TResponse>(long actorId, long nodeId, TRequest request)
        where TRequest : IMessage<TRequest>, new()
        where TResponse : IMessage<TResponse>, new()
    {
        var targetNode = nodeManager.FindNode(nodeId);
        if (targetNode is null || targetNode.IsClose)
            throw new InvalidOperationException($"Failed to find target node {nodeId}");

        return RequestInternalAsync<TRequest, TResponse>(actorId, targetNode, request);
    }

    private async Task<TResponse> RequestInternalAsync<TRequest, TResponse>(long actorId, RemoteNode targetNode,
        TRequest message)
        where TRequest : IMessage<TRequest>, new()
        where TResponse : IMessage<TResponse>, new()
    {
        var requestKey = requestCache.GetRequestKey();

        var packet = NodePacket.Create(actorId, NodeConfig.NodeId, targetNode.Identity, requestKey, false, message);

        // Distributed Tracing: Client span (샘플링 기반)
        var msgName = AutoGeneratedParsers.GetNameById(packet.Header.MsgId);
        using var activity = TelemetryHelper.Source.HasListeners()
            ? TelemetryHelper.Source.StartActivity($"Node.RPC {msgName}", ActivityKind.Client)
            : null;
        if (activity != null)
        {
            activity.SetTag("rpc.system", "netmq");
            activity.SetTag("rpc.method", msgName);
            activity.SetTag("rpc.service", targetNode.Identity.ToString());
            activity.SetTag("net.peer.id", targetNode.Identity);
        }

        TelemetryHelper.InjectContext(ref packet.Header);
        packet.WriteHeader();

        var responseTask = requestCache.PendingAsync(requestKey);
        nodeCommunicator.Send(targetNode.IdentityBytes, packet);
        using var response = await responseTask;

        var parser = AutoGeneratedParsers.GetParserById(response.Header.MsgId);
        Debug.Assert(parser != null);

        return (TResponse) parser.ParseFrom(response.Payload);
    }
}