#nullable enable
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace PacketParserGenerator
{
    /// <summary>
    /// Proto 어셈블리 자동 로딩 Source Generator
    /// 컴파일 참조에서 프로토 어셈블리를 탐색하여 [ModuleInitializer]를 생성합니다.
    /// const MsgId 인라인으로 인해 로드되지 않는 프로토 어셈블리의 ModuleInitializer를 강제 실행합니다.
    /// 앱 프로젝트에서는 엔트리 어셈블리이므로 자동 실행이 보장됩니다.
    /// </summary>
    [Generator]
    public class ProtoTraceGenerator : IIncrementalGenerator
    {
        /// <summary>
        ///
        /// </summary>
        /// <param name="context"></param>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(
                context.CompilationProvider,
                Execute);
        }

        private void Execute(SourceProductionContext context, Compilation compilation)
        {
            var protoAssemblyTypes = FindProtoAssemblyTypes(compilation);
            if (protoAssemblyTypes.Count == 0) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();
            sb.AppendLine("namespace SimpleNetEngine.ProtoAutoGen");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 참조된 외부 Proto 어셈블리의 [ModuleInitializer]를 강제 실행합니다.");
            sb.AppendLine("    /// const MsgId 인라인으로 어셈블리가 로드되지 않는 문제를 해결합니다.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    internal static class ProtoAssemblyLoader");
            sb.AppendLine("    {");
            sb.AppendLine("        [ModuleInitializer]");
            sb.AppendLine("        internal static void LoadReferencedProtoAssemblies()");
            sb.AppendLine("        {");

            var emittedModules = new HashSet<string>();
            foreach (var protoType in protoAssemblyTypes)
            {
                var lastDot = protoType.LastIndexOf('.');
                var moduleKey = lastDot >= 0 ? protoType.Substring(0, lastDot) : protoType;
                if (emittedModules.Add(moduleKey))
                {
                    sb.AppendLine($"            RuntimeHelpers.RunModuleConstructor(typeof({protoType}).Module.ModuleHandle);");
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("ProtoAssemblyLoader.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static List<string> FindProtoAssemblyTypes(Compilation compilation)
        {
            var result = new List<string>();

            foreach (var reference in compilation.ExternalReferences)
            {
                if (compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol assemblySymbol)
                    continue;

                if (SymbolEqualityComparer.Default.Equals(assemblySymbol, compilation.Assembly))
                    continue;

                var initType = assemblySymbol.GetTypeByMetadataName("SimpleNetEngine.ProtoAutoGen.AutoGeneratedInitializer");
                if (initType == null)
                    continue;

                var publicType = FindPublicProtoType(assemblySymbol.GlobalNamespace);
                if (publicType != null)
                {
                    result.Add($"global::{publicType}");
                }
            }

            return result;
        }

        private static string? FindPublicProtoType(INamespaceSymbol ns)
        {
            foreach (var type in ns.GetTypeMembers())
            {
                if (type.DeclaredAccessibility == Accessibility.Public &&
                    type.GetMembers("MsgId").Any(m => m is IFieldSymbol f && f.IsConst))
                {
                    return type.ToDisplayString();
                }
            }

            foreach (var childNs in ns.GetNamespaceMembers())
            {
                var found = FindPublicProtoType(childNs);
                if (found != null) return found;
            }

            return null;
        }
    }
}
