using System.Diagnostics;
using Google.Protobuf;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using SimpleNetEngine.Infrastructure.Telemetry;
using SimpleNetEngine.Protocol.Packets;
using SimpleNetEngine.ProtoGenerator;
using SimpleNetEngine.Node.Network;

namespace SimpleNetEngine.Node.Core;

/// <summary>
/// Stateless Service용 Node 패킷 처리기.
/// INodeDispatcher를 사용하여 [NodeController] + [NodePacketHandler] 기반 핸들러로 라우팅합니다.
/// Parallel 모드로 동작하며, ActorId가 있으면 per-ActorId 큐로 순차 보장합니다.
/// </summary>
public class StatelessEventController : ParallelNodeEventHandler
{
    private readonly INodeDispatcher _dispatcher;
    private readonly INodeResponser _responser;
    private readonly IServiceScopeFactory _scopeFactory;

    public StatelessEventController(
        ILogger<StatelessEventController> logger,
        INodeDispatcher dispatcher,
        INodeResponser responser,
        IServiceScopeFactory scopeFactory) : base(logger)
    {
        _dispatcher = dispatcher;
        _responser = responser;
        _scopeFactory = scopeFactory;
    }

    protected override async Task ProcessPacketInternalAsync(NodePacket packet)
    {
        IMessage? response = null;
        using (packet)
        {
            try
            {
                // Distributed Tracing: Server span (샘플링 기반)
                var msgName = AutoGeneratedParsers.GetNameById(packet.Header.MsgId);
                using var activity = TelemetryHelper.Source.HasListeners()
                    ? TelemetryHelper.ExtractAndStartActivity(in packet.Header, $"Node.RPC {msgName}", ActivityKind.Server)
                    : null;
                if (activity != null)
                {
                    activity.SetTag("rpc.system", "netmq");
                    activity.SetTag("rpc.method", msgName);
                    activity.SetTag("net.peer.id", packet.Header.Source);
                }

                await using var scope = _scopeFactory.CreateAsyncScope();
                response = await _dispatcher.DispatchAsync(scope.ServiceProvider, packet);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Error processing stateless packet");
            }

            if (response != null)
                _responser.Response(packet.Header, response);
        }
    }
}
