using System.Runtime.InteropServices;
using Google.Protobuf;
using NetMQ;
using SimpleNetEngine.ProtoGenerator;

namespace SimpleNetEngine.Protocol.Packets;

// ---------------------------------------------------------
// NodePacket (Node ↔ Node ServiceMesh 패킷)
// ---------------------------------------------------------
public class NodePacket : IDisposable
{
    public const long ServerActorId = 0;
    public NodeHeader Header;
    public Msg Msg;

    public Span<byte> Payload => Msg.Slice(NodeHeader.Size, Msg.Size - NodeHeader.Size);

    private NodePacket() {}

    public static NodePacket Create(ref Msg msg)
    {
        var packet = new NodePacket();
        packet.Header = MemoryMarshal.Read<NodeHeader>(msg.Slice());
        packet.Msg.Move(ref msg);
        return packet;
    }

    public static NodePacket Create(long actorId, long srcId, long destId, int requestKey, bool isReply, IMessage message)
    {
        var msgId = AutoGeneratedParsers.GetIdByInstance(message);
        int payloadLen = message.CalculateSize();

        var packet = new NodePacket();
        packet.Msg.InitPool(NodeHeader.Size + payloadLen);

        packet.Header = new NodeHeader
        {
            ActorId = actorId,
            Source = srcId,
            Dest = destId,
            RequestKey = requestKey,
            IsReply = isReply ? (byte)1 : (byte)0,
            MsgId = msgId
        };

        MemoryMarshal.Write(packet.Msg.Slice(0, NodeHeader.Size), in packet.Header);
        message.WriteTo(packet.Msg.Slice(NodeHeader.Size, payloadLen));
        return packet;
    }

    /// <summary>
    /// Header 필드 변경 후 Msg 버퍼에 재직렬화
    /// </summary>
    public void WriteHeader()
    {
        MemoryMarshal.Write(Msg.Slice(0, NodeHeader.Size), in Header);
    }

    public void Dispose()
    {
        if (Msg.IsInitialised) Msg.Close();
    }
}
