using Game.Protocol;
using Internal.Protocol;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using SimpleNetEngine.Game.Actor;
using SimpleNetEngine.Game.Core;
using SimpleNetEngine.Game.Extensions;
using SimpleNetEngine.Node.Network;
using SimpleNetEngine.Protocol.Packets;
using SimpleNetEngine.ProtoGenerator;

namespace SimpleNetEngine.Game.Controllers;

/// <summary>
/// 라이브러리 내장 HandshakeReq 핸들러
/// 클라이언트가 ReadyToHandshakeNtf 수신 후 보내는 첫 번째 패킷 처리
///
/// Source Generator는 현재 컴파일만 스캔하므로 라이브러리 컨트롤러는 수동 등록 필요.
/// GameServiceExtensions.RegisterBuiltInHandlers()에서 등록됨.
/// </summary>
public class HandshakeController(
    ILogger<HandshakeController> logger,
    INodeSender nodeSender)
{
    /// <summary>
    /// HandshakeReq 처리: ECDH 키 교환 + Actor 상태 전환 + HandshakeRes 응답
    /// Actor는 이미 ConnectionController.HandleNtfNewUser에서 생성됨
    ///
    /// ECDH Flow:
    /// 1. 클라이언트 ECDH 공개키 추출 (HandshakeReq.ClientEphemeralPublicKey)
    /// 2. Gateway에 ActivateEncryption RPC 전송 (클라이언트 공개키 전달)
    /// 3. Gateway가 SharedSecret 도출 → AES-GCM 암호화 활성화
    /// 4. HandshakeRes에 Gateway ECDH 공개키 포함하여 클라이언트에 반환 (평문)
    /// 5. 클라이언트가 암호화 활성화 후 LoginGameReq 전송 → LoginGameRes로 ReconnectKey 전달 (암호화)
    /// </summary>
    public async Task<Response> HandleHandshake(ISessionActor actor, HandshakeReq req)
    {
        logger.LogInformation("HandshakeReq received: ActorId={ActorId}, Status={Status}", actor.ActorId, actor.Status);

        // Actor 상태를 Authenticating으로 전환 (핸드셰이크 완료 → 인증 대기)
        actor.Status = ActorState.Authenticating;

        // ECDH 키 교환: Gateway에 클라이언트 공개키를 전달하여 암호화 활성화
        byte[]? gatewayEphemeralPublicKey = null;
        if (!req.ClientEphemeralPublicKey.IsEmpty &&
            actor.State.TryGetValue("GatewayEphemeralPublicKey", out var gwPubKeyObj) &&
            gwPubKeyObj is byte[] gwPubKey)
        {
            gatewayEphemeralPublicKey = gwPubKey;

            // Gateway에 ActivateEncryption RPC 전송
            var activateReq = new ServiceMeshActivateEncryptionReq
            {
                SessionId = actor.ActorId,
                ClientEphemeralPublicKey = Google.Protobuf.ByteString.CopyFrom(req.ClientEphemeralPublicKey.ToByteArray())
            };

            var activateRes = await nodeSender.RequestAsync<ServiceMeshActivateEncryptionReq, ServiceMeshActivateEncryptionRes>(
                NodePacket.ServerActorId,
                actor.GatewayNodeId,
                activateReq);

            if (!activateRes.Success)
            {
                logger.LogWarning("ActivateEncryption failed: ActorId={ActorId}, Gateway={GatewayNodeId}",
                    actor.ActorId, actor.GatewayNodeId);
            }
            else
            {
                logger.LogInformation("Encryption activated: ActorId={ActorId}, Gateway={GatewayNodeId}",
                    actor.ActorId, actor.GatewayNodeId);
            }

            // 사용 완료 후 Actor 상태에서 제거
            actor.State.Remove("GatewayEphemeralPublicKey");
        }

        // ECDSA 서명 추출 (있는 경우)
        byte[]? gatewaySignature = null;
        if (actor.State.TryGetValue("GatewayEphemeralSignature", out var sigObj) && sigObj is byte[] sig)
        {
            gatewaySignature = sig;
            actor.State.Remove("GatewayEphemeralSignature");
        }

        // ReconnectKey는 HandshakeRes에 포함하지 않음 (평문 노출 방지)
        // 인증 성공 후 LoginGameRes(암호화)로 전달
        var response = new HandshakeRes
        {
            ServerEphemeralPublicKey = gatewayEphemeralPublicKey != null
                ? Google.Protobuf.ByteString.CopyFrom(gatewayEphemeralPublicKey)
                : Google.Protobuf.ByteString.Empty,
            ServerEphemeralSignature = gatewaySignature != null
                ? Google.Protobuf.ByteString.CopyFrom(gatewaySignature)
                : Google.Protobuf.ByteString.Empty
        };

        logger.LogInformation("HandshakeRes sent: ActorId={ActorId}, HasEncryption={HasEncryption}",
            actor.ActorId, gatewayEphemeralPublicKey != null);

        // HandshakeRes는 암호화 전에 전송 (아직 클라이언트가 키를 모르므로 평문)
        return Response.Ok(response);
    }

    /// <summary>
    /// MessageDispatcher에 내장 핸들러를 수동 등록
    /// Source Generator가 스캔하지 못하는 라이브러리 컨트롤러용
    /// </summary>
    public static void RegisterHandlers(MessageDispatcher dispatcher)
    {
        dispatcher.RegisterHandler(HandshakeReq.MsgId, async (sp, actor, payload) =>
        {
            var parser = AutoGeneratedParsers.GetParserById(HandshakeReq.MsgId);
            if (parser == null) return null;

            var (header, message) = PacketHelper.ParseClientPacket(payload.Span, parser);
            var controller = sp.GetRequiredService<HandshakeController>();
            return await controller.HandleHandshake(actor, (HandshakeReq)message);
        }, [ActorState.Created]);
    }
}
