using Game.Protocol;
using Microsoft.Extensions.DependencyInjection;
using SimpleNetEngine.Game.Actor;
using SimpleNetEngine.Game.Core;
using SimpleNetEngine.Game.Extensions;
using SimpleNetEngine.Protocol.Packets;
using SimpleNetEngine.ProtoGenerator;

namespace SimpleNetEngine.Game.Controllers;

/// <summary>
/// Heartbeat + TimeSync 핸들러
/// - PingReq: 클라이언트 idle 시 전송, PongRes 응답
/// - TimeSyncReq: 10초 주기 강제 전송, 서버 시간 첨부하여 TimeSyncRes 응답
/// Actor mailbox를 통과하므로 TouchActivity()가 자동 호출됨.
///
/// Source Generator는 현재 컴파일만 스캔하므로 라이브러리 컨트롤러는 수동 등록 필요.
/// GameServiceExtensions.RegisterBuiltInHandlers()에서 등록됨.
/// </summary>
public class HeartbeatController
{
    public Response HandlePing(ISessionActor actor, PingReq req)
    {
        return Response.Ok(new PongRes { Timestamp = req.Timestamp });
    }

    public Response HandleTimeSync(ISessionActor actor, TimeSyncReq req)
    {
        return Response.Ok(new TimeSyncRes
        {
            ClientSendTimestamp = req.ClientSendTimestamp,
            ServerTimestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()
        });
    }

    /// <summary>
    /// MessageDispatcher에 내장 핸들러를 수동 등록
    /// </summary>
    public static void RegisterHandlers(MessageDispatcher dispatcher)
    {
        dispatcher.RegisterHandler(PingReq.MsgId, (sp, actor, payload) =>
        {
            var parser = AutoGeneratedParsers.GetParserById(PingReq.MsgId);
            if (parser == null) return Task.FromResult<Response?>(null);

            var (header, message) = PacketHelper.ParseClientPacket(payload.Span, parser);
            var controller = sp.GetRequiredService<HeartbeatController>();
            return Task.FromResult<Response?>(controller.HandlePing(actor, (PingReq)message));
        }, [ActorState.Active]);

        dispatcher.RegisterHandler(TimeSyncReq.MsgId, (sp, actor, payload) =>
        {
            var parser = AutoGeneratedParsers.GetParserById(TimeSyncReq.MsgId);
            if (parser == null) return Task.FromResult<Response?>(null);

            var (header, message) = PacketHelper.ParseClientPacket(payload.Span, parser);
            var controller = sp.GetRequiredService<HeartbeatController>();
            return Task.FromResult<Response?>(controller.HandleTimeSync(actor, (TimeSyncReq)message));
        }, [ActorState.Active]);
    }
}
