using Game.Protocol;
using Microsoft.Extensions.DependencyInjection;
using SimpleNetEngine.Game.Actor;
using SimpleNetEngine.Game.Core;
using SimpleNetEngine.Game.Extensions;
using SimpleNetEngine.Protocol.Packets;
using SimpleNetEngine.ProtoGenerator;

namespace SimpleNetEngine.Game.Controllers;

/// <summary>
/// Heartbeat PingReq 핸들러
/// 클라이언트가 idle 시 전송하는 PingReq를 수신하여 PongRes 응답.
/// Actor mailbox를 통과하므로 TouchActivity()가 자동 호출됨.
///
/// Source Generator는 현재 컴파일만 스캔하므로 라이브러리 컨트롤러는 수동 등록 필요.
/// GameServiceExtensions.RegisterBuiltInHandlers()에서 등록됨.
/// </summary>
public class HeartbeatController
{
    public Response HandlePing(ISessionActor actor, PingReq req)
    {
        return Response.Ok(new PongRes { Timestamp = req.Timestamp });
    }

    /// <summary>
    /// MessageDispatcher에 내장 핸들러를 수동 등록
    /// </summary>
    public static void RegisterHandlers(MessageDispatcher dispatcher)
    {
        dispatcher.RegisterHandler(PingReq.MsgId, (sp, actor, payload) =>
        {
            var parser = AutoGeneratedParsers.GetParserById(PingReq.MsgId);
            if (parser == null) return Task.FromResult<Response?>(null);

            var (header, message) = PacketHelper.ParseClientPacket(payload.Span, parser);
            var controller = sp.GetRequiredService<HeartbeatController>();
            return Task.FromResult<Response?>(controller.HandlePing(actor, (PingReq)message));
        }, [ActorState.Active]);
    }
}
